services:
  nanobot:
    build:
      context: .
      dockerfile: nanobot/Dockerfile
      args:
        REGISTRY_PREFIX_DOCKER_HUB: ""
    restart: unless-stopped
    networks:
      - lms-network
    environment:
      - LLM_API_KEY=not-needed
      - LLM_API_BASE_URL=http://qwen-code-api:8080/v1
      - NANOBOT_LMS_BACKEND_URL=http://backend:8000
      - NANOBOT_LMS_API_KEY=lms-api-key
      - NANOBOT_ACCESS_KEY=02051955
      - NANOBOT_GATEWAY_CONTAINER_ADDRESS=0.0.0.0
      - NANOBOT_GATEWAY_CONTAINER_PORT=18790
      - NANOBOT_WEBCHAT_CONTAINER_ADDRESS=0.0.0.0
      - NANOBOT_WEBCHAT_CONTAINER_PORT=8765
      - VICTORIALOGS_URL=http://victorialogs:9428
      - VICTORIATRACES_URL=http://victoriatraces:10428
    depends_on:
      - backend
      - qwen-code-api

  client-web-flutter:
    build:
      context: ./nanobot-websocket-channel/client-web-flutter
      args:
        REGISTRY_PREFIX_DOCKER_HUB: ""
        REGISTRY_PREFIX_GHCR: ""
    volumes:
      - client-web-flutter:/output

  caddy:
    depends_on:
      - nanobot
      - client-web-flutter
    environment:
      - NANOBOT_WEBCHAT_CONTAINER_PORT=8765
    volumes:
      - client-web-flutter:/srv/flutter:ro


volumes:
  client-web-flutter:
